hyphenate text
abey79/vpype pull request #668
Opened 2023-10-08 10:51 UTC by pepijndevos

#### Description

This PR adds hyphenation to the word wrapping functionality. Example:

![image](https://github.com/abey79/vpype/assets/168609/8c56ed9e-15a5-4f6f-a06d-be51d8407449)

This needs a `poetry add pyphen` or similar but these things tend to create conflicts so I'd save that until all the tests and docs and API and bikeshedding is done.

#### Checklist

- [ ] feature/fix implemented
- [ ] code formatting ok (`black` and `ruff check .`)
- [ ] `mypy` returns no error
- [ ] tests added/updated and `pytest` succeeds
- [ ] add Pyphen dependency
- [ ] make configurable
- [ ] documentation added/updated
    - [ ] command docstring and option/argument `help`
    - [ ] README.md updated (Feature Overview)
    - [ ] CHANGELOG.md updated
    - [ ] added new command to `reference.rst`
    - [ ] RTD doc updated and building with no error (`make clean && make html` in `docs/`)

2023-10-08 16:03 UTC, abey79 requested changes
Great contribution, thanks!

You will have to add the dependency to `pyproject.toml` for the CI to have a chance to succeed. 

Also, it would be nice to add the corresponding parameters to the `text` command in `vpype_cli`, and update all the docstrings.

2023-10-08 16:51 UTC, pepijndevos commented on vpype/text.py
> +    hyphenate="en",
I would think of doing `--hyphenate en` and make it also `str | None` maybe?

2023-10-08 18:09 UTC, abey79 commented on vpype/text.py
> +    hyphenate="en",
Yeah I guess that would work as well.

2023-10-08 19:48 UTC, pepijndevos commented
Alright, I think that should be most of the relevant changes?

2023-10-13 17:05 UTC, abey79 approved these changes
Looks good! Just a small comment on the docs to point at the right format to specify the language.

2023-10-13 17:05 UTC, abey79 commented on vpype_cli/text.py
> +    language code.
Same here.

2023-10-13 17:05 UTC, abey79 commented on vpype/text.py
> +        hyphenate: wrapped text is hyphenated with the given language (default: None)
It would be great to indicate what format(s) are acceptable for the language, and provide a couple of examples.

2023-10-13 18:33 UTC, pepijndevos commented
Something like this? Also caught a leftover print statement

2023-10-13 19:22 UTC, abey79 commented
> Something like this? Also caught a leftover print statement

That works yes. Ready to merge as soon as CI is happy!

2023-10-13 20:13 UTC, pepijndevos commented
darn that little doc addition make ruff unhappy

2023-10-15 14:04 UTC, merged